export const FETCH_REPOS_REQUEST = 'FETCH_REPOS_REQUEST';
export const FETCH_REPOS_SUCCESS = 'FETCH_REPOS_SUCCESS';
export const FETCH_REPOS_FAIL = 'FETCH_REPOS_FAIL';

export const UPDATE_REPO_REQUEST = 'UPDATE_REPO_REQUEST';
export const UPDATE_REPO_SUCCESS = 'UPDATE_REPO_SUCCESS';
export const UPDATE_REPO_FAIL = 'UPDATE_REPO_FAIL';
